# Generated by Django 6.0.3 on 2026-04-25 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('service', models.CharField(choices=[('removal', 'Bee Removal'), ('pollination', 'Pollination Service'), ('education', 'Education Service'), ('hive_setup', 'Hive Set-Up')], default='removal', max_length=20)),
                ('message', models.TextField(max_length=999999)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='submissions/photos/')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.submission')),
            ],
        ),
    ]
