# Generated by Django 5.2.7 on 2026-04-04 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField()),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("removal", "Bee Removal"),
                            ("pollination", "Pollination Service"),
                            ("education", "Education Service"),
                            ("hive_setup", "Hive Set-Up"),
                        ],
                        default="bee_removal",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SubmissionImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="submissions/photos/")),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="contact.submission",
                    ),
                ),
            ],
        ),
    ]
