# Generated by Django 5.2.7 on 2026-04-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="email",
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name="submission",
            name="message",
            field=models.TextField(max_length=999),
        ),
        migrations.AlterField(
            model_name="submission",
            name="phone",
            field=models.CharField(max_length=12),
        ),
    ]
